server:
  port: 9601
spring:
  profiles:
    active: dev
  application:
    name: micro-knife4j-order
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
